server:
  port: 8080

logging:
  level:
    root: WARN
    mx.com.ia.pymefectivo.email: TRACE
    mx.com.ia.pymefectivo.repository: TRACE
  
mail:
  host: smtp.gmail.com
  port: 465
  username: atn_servpyme@independencia.com.mx
  password: Findep200201
  properties:
    mail:
      smtp:
        auth: true
        starttls: true
      
db:
  ip: 172.12.0.1
  port: 3306
  name: pymefectivo
  user: pymefectivo
  pass: pymefectivo1234
  url: jdbc:mysql://127.12.0.1:3306/pymefectivo?serverTimezone=UTC&useLegacyDatetimeCode=false
  instancia: findep-desarrollo-170215:us-central1:findep-mysql
  
email:
  mailTo: out_fcamachol@independencia.com.mx,out_rguerrerop@independencia.com.mx,out_djimenezj@masnomina.com.mx,out_lpisilc@independencia.com.mx,ycarius@independencia.com.mx 
  host: smtp.gmail.com
  port: 465
  user: atn_servpyme@independencia.com.mx
  pass: Findep200201